pages/urls.py
from django.urls import path

from .views import (
    HomeView, 
    PricingListView, 
    AboutPageView,
    ContactView,
    Suscribir
)



app_name = 'pages'
urlpatterns = [

    path('', HomeView.as_view(), name='index'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('pricing/', PricingListView.as_view(), name='pricing'),
    path('suscribirse/' ,Suscribir.as_view(), name='suscribirse'),
    
]

payment/urls.py
from django.urls import path 

from .views import (
	PaymentView, 
	CreateSubscriptionView, 
	ChangeSubscriptionView,
	RetryInvoiceView,
	webhook
)


app_name = 'payments'
urlpatterns = [

	path('plan/<slug>/', PaymentView.as_view(), name='checkout'),
	path('create-subscription/', CreateSubscriptionView.as_view(), name='create-subscription'),
	path('change-subscription/', ChangeSubscriptionView.as_view(), name='change-subscription'),
	path('retry-invoice/', RetryInvoiceView.as_view(), name='retry-invoice'),
	path('webhook/', webhook, name='webhook'),

]

users/urls.py
from django.urls import path


from .views import (
	SignupPageView,
	user_update_view,
	user_detail_view,
	user_redirect_view,
	UserSubscriptionView,
	CancelSubscriptionView,
)

app_name = 'users'
urlpatterns = [

	path("~redirect/", view=user_redirect_view, name="redirect"),
	path("~update/", view=user_update_view, name="update"),
	path("<str:username>/", view=user_detail_view, name="detail"),
	path("<str:username>/subscription/", UserSubscriptionView.as_view(), name="subscription"),
    path("<str:username>/subscription/cancel/", CancelSubscriptionView.as_view(), name="cancel-subscription"),
	path('signup/', SignupPageView.as_view(), name='signup'),

]

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="bg-light py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12 mb-0"><a href="index.html">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">About</strong></div>
      </div>
    </div>
  </div>  

  <div class="site-section border-bottom about" data-aos="fade">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-6">
          <div class="block-16">
            <figure>
              <img src="{% static 'css/img/about.jpg' %}" alt="Image placeholder" class="img-fluid rounded">
              <!-- <a href="https://vimeo.com/channels/staffpicks/93951774" class="play-button popup-vimeo"><span class="ion-md-play"></span></a> -->

            </figure>
          </div>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-5">
          
          
          <div class="site-section-heading pt-3 mb-4">
            <h2 class="text-black">How We Started</h2>
          </div>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius repellat, dicta at laboriosam, nemo exercitationem itaque eveniet architecto cumque, deleniti commodi molestias repellendus quos sequi hic fugiat asperiores illum. Atque, in, fuga excepturi corrupti error corporis aliquam unde nostrum quas.</p>
          <p>Accusantium dolor ratione maiores est deleniti nihil? Dignissimos est, sunt nulla illum autem in, quibusdam cumque recusandae, laudantium minima repellendus.</p>
          
        </div>
      </div>
    </div>
  </div>

  <div class="site-section border-bottom" data-aos="fade">
    <div class="container">
      <div class="row justify-content-center mb-5">
        <div class="col-md-7 site-section-heading text-center pt-4">
          <h2>The Team</h2>
          <div class="heading-underline"></div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-lg-3">

          <div class="block-38 text-center">
            <div class="block-38-img">
              <div class="block-38-header">
                <img src="{% static 'css/img/person_1.jpg' %}" alt="Image placeholder" class="mb-4">
                <h3 class="block-38-heading h4">Elizabeth Graham</h3>
                <p class="block-38-subheading">CEO/Co-Founder</p>
              </div>
              <div class="block-38-body">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta. </p>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3">
          <div class="block-38 text-center">
            <div class="block-38-img">
              <div class="block-38-header">
                <img src="{% static 'css/img/person_2.jpg' %}" alt="Image placeholder" class="mb-4">
                <h3 class="block-38-heading h4">Jennifer Greive</h3>
                <p class="block-38-subheading">Co-Founder</p>
              </div>
              <div class="block-38-body">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta. </p>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3">
          <div class="block-38 text-center">
            <div class="block-38-img">
              <div class="block-38-header">
                <img src="{% static 'css/img/person_3.jpg' %}" alt="Image placeholder" class="mb-4">
                <h3 class="block-38-heading h4">Patrick Marx</h3>
                <p class="block-38-subheading">Marketing</p>
              </div>
              <div class="block-38-body">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta. </p>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3">
          <div class="block-38 text-center">
            <div class="block-38-img">
              <div class="block-38-header">
                <img src="{% static 'css/img/person_4.jpg' %}" alt="Image placeholder" class="mb-4">
                <h3 class="block-38-heading h4">Mike Coolbert</h3>
                <p class="block-38-subheading">Sales Manager</p>
              </div>
              <div class="block-38-body">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta. </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="site-section site-section-sm site-blocks-1 border-0 about-icon" data-aos="fade">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="">
          <div class="icon mr-4 align-self-start">
            <i class="fa fa-line-chart fa-3x" aria-hidden="true"></i>
          </div>
          <div class="text">
            <h2 class="text-uppercase">Quality</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="100">
          <div class="icon mr-4 align-self-start">
            <i class="fa fa-child fa-3x" aria-hidden="true"></i>
          </div>
          <div class="text">
            <h2 class="text-uppercase">For Everyone</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="200">
          <div class="icon mr-4 align-self-start">
            <i class="fa fa-search-plus fa-3x" aria-hidden="true"></i>
          </div>
          <div class="text">
            <h2 class="text-uppercase">Searching</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!--- Footer -->
<footer>
	<div class="container-fluid text-center">
		<div class="row text-center">
			<div class="col-md-4">
				<img src="https://getbootstrap.com/docs/4.5/assets/brand/bootstrap-solid.svg">
				<hr class="light">
				<p>555-555-5555</p>
				<p>email@email.com</p>
				<p>100 Street None</p>
				<p>City, State, 00000</p>
			</div>
			<div class="col-md-4">
				<hr class="light">
				<h5>Our hours</h5>
				<hr class="light">
				<p>Monday 9am - 5pm</p>
        <p>Saturday 10am - 4pm</p>
        <p>Monday 9am - 5pm</p>
				<p>Saturday 10am - 4pm</p>
      </div>
      <div class="col-md-4">
				<hr class="light">
				<h5>Services Area</h5>
				<hr class="light">
				<p>City, Zip Code</p>
        <p>City, Zip Code</p>
        <p>City, Zip Code</p>
				<p>City, Zip Code</p>
      </div>
      
      
    </div>
    <hr class="socket">
    &copy; Davijhon Theme.
	</div>
</footer>
<!--- Footer -->
{% endblock content %}

templates/pages/contact.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- Page Content -->

    <!-- Page Heading/Breadcrumbs -->
    <div class="col-12">
    <h1 class="contact-title">Contact
    </h1>
  </div>
    <!-- Content Row -->
    <div class="container-fluid">
    <div class="row contact">
      <!-- Map Column -->
      <div class="col-lg-8 mb-4">
        <!-- Embedded Google Map -->
        <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe>
      </div>
      <!-- Contact Details Column -->
      <div class="col-lg-4 mb-4">
        <h3>Contact Details</h3>
        <p>
          {{ contact.direccion }}
          <br>{{ contact.direccion }}
          <br>
        </p>
        <p>
          <i class="fas fa-mobile-alt"></i> {{ contact.telefono }}
        </p>
        <p>
          <i class="fas fa-at"></i>
          <a href="#">{{ contact.email }}
          </a>
        </p>
        <p>
          <i class="far fa-clock"></i> Monday - Friday: 9:00 AM to 5:00 PM
        </p>
      </div>
    </div>
    <!-- /.row -->

    <!-- Contact Form -->
    <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
    <div class="row contact-form">
      <div class="col-lg-8 mb-4">
        <h3>Send us a Message</h3>
        <form method="POST" name="sentMessage">
          {% csrf_token %}
            <div class="control-group form-group">
              <div class="controls">
                <label>Full Name:</label>
                {{ form.nombre }}
                <!--input type="text" class="form-control" id="name" required data-validation-required-message="Please enter your name."-->
                <p class="help-block"></p>
              </div>
            </div>
            <div class="control-group form-group">
              <div class="controls">
                <label>Email Address:</label>
                {{ form.correo }}
                <!--input type="email" class="form-control" id="email" required data-validation-required-message="Please enter your email address.">
              </div-->
              <p class="help-block"></p>
            </div>
            <div class="control-group form-group">
              <div class="controls">
                <label>Subject:</label>
                {{ form.asunto }}
                <!--input type="email" class="form-control" id="email" required data-validation-required-message="Please enter your email address.">
              </div-->
              <p class="help-block"></p>
            </div>
            <div class="control-group form-group">
              <div class="controls">
                <label>Message:</label>
                {{ form.mensaje }}
              </div>
            </div>
            <!-- For success/fail messages -->
            <button type="submit" class="btn btn-primary">Send Message</button>
        </form>
      </div>
    </div>
  </div>
    <!-- /.row -->


    {% include 'pages/footer.html' %}
{% endblock content %}

templates/pages/footer.html
<footer class="footer bg-light">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
        <ul class="list-inline mb-2">
          <li class="list-inline-item">
            <a href="#">About</a>
          </li>
          <li class="list-inline-item">&sdot;</li>
          <li class="list-inline-item">
            <a href="#">Contact</a>
          </li>
          <li class="list-inline-item">&sdot;</li>
          <li class="list-inline-item">
            <a href="#">Terms of Use</a>
          </li>
          <li class="list-inline-item">&sdot;</li>
          <li class="list-inline-item">
            <a href="#">Privacy Policy</a>
          </li>
        </ul>
        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2019. All Rights Reserved.</p>
      </div>
      <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
        <ul class="list-inline mb-0">
          <li class="list-inline-item mr-3">
            <a href="#">
              <i class="fab fa-facebook fa-2x fa-fw"></i>
            </a>
          </li>
          <li class="list-inline-item mr-3">
            <a href="#">
              <i class="fab fa-twitter-square fa-2x fa-fw"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <i class="fab fa-instagram fa-2x fa-fw"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

templates/pages/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div id="carouselExampleCaptions" class="carousel slide carousel-fade" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{{ carousel_image1.img.url }}" class="d-block w-100" alt="...">
        {% if carousel_image1.caption_title and carousel_image1.caption_content and carousel_image1.caption_button %}
          <div class="carousel-caption d-none d-md-block">
            <h1>{{ carousel_image1.caption_title }}</h1>
            <h3>{{ carousel_image1.caption_content }}</h3>
            <!-- <h3>a pharetra augue mollis interdum.</h3> -->
            <a href="{{ carousel_image1.caption_button }}"><button type="button" class="btn btn-outline-secondary btn-lg">get start</button></a>
          </div>
        {% endif %}
      </div>
      <div class="carousel-item">
        <img src="{{ carousel_image2.img.url }}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{{ carousel_image3.img.url }}" class="d-block w-100" alt="...">
      </div>
    </div>
</div>

<!-- Start Section 1 -->
<div class="container-fluid">
  <div class="row valores padding">
    <div class="col-md-4">
      <h3 class="text-center">Etherun</h3>
      <div class="heading-underline"></div>
      <blockquote>
        <i class="fa fa-quote-left" aria-hidden="true"></i>
        Etherun martes malis paremis elis tatus samen siri al tamen eres, tarin karen malemium
        palserin enamenom varin lenin asule
      </blockquote>
    </div>
    <div class="col-md-4">
      <h3 class="text-center">Roselin</h3>
      <div class="heading-underline"></div>
      <blockquote>
        <i class="fa fa-quote-left" aria-hidden="true"></i>
        Roselin fares malgun, etis paremis jalen, etemon talin damelon. Etimus falin jelinomen 
        parelemun atominer salme
      </blockquote>
    </div>
    <div class="col-md-4">
      <h3 class="text-center">Doran</h3>
      <div class="heading-underline"></div>
      <blockquote>
        <i class="fa fa-quote-left" aria-hidden="true"></i>
        Doran, eminer faltorem equietamus al sular dolorin samen tatis. Cusamer falis eremus, etis 
        karen vazil.
      </blockquote>
    </div>
  </div>
  <hr class="my-4">
</div>
<!-- End Section 1 -->

<!-- Start Background Fixed Image -->
<div id="fixed">	
</div>
<!-- End Background Fixed Image -->

<!-- Start Section 2 -->
<div class="container-fluid padding">
	<div class="row text-center padding">
		<div class="col-xs-12 col-sm-6 col-md-4 padding">
      <i class="fa fa-line-chart fa-3x" aria-hidden="true"></i>
			<h3>Quality</h3>
      <p>Built with the leates version of HTML, HTML5, teris asterum campen mellis eberatun taram</p>

		</div>
		<div class="col-xs-12 col-sm-6 col-md-4 padding">
      <i class="fa fa-child fa-3x" aria-hidden="true"></i>
			<h3>For Everyone</h3>
      <p>Built with the leates version of BOOTSTRAP, teris asterum campen mellis eberatun taram</p>

		</div>
		<div class="col-sm-12 col-md-4 padding">
      <i class="fa fa-search-plus fa-3x" aria-hidden="true"></i>
			<h3>Searching</h3>
      <p>Built with the leates version of css3, teris asterum campen mellis eberatun taram</p>

		</div>
	</div>
	<hr class="my-4">
</div>
<!-- End Section 2 -->

<div class="col-12">
  <h3 class="heading text-center">How we work</h3>
  <div class="heading-underline"></div>
</div>	

<!-- Start Section 3 Jumbotron -->
<div class="jumbotron"> <!-- Star Jumbotron-->
  <div class="container-fluid p-0"><!-- Start Container Fluid -->

      <div class="row rowone"> <!-- Start Firts Row -->
          <div class="col-lg-4 order-lg-2 jumbotron-img">
              <img src="{% static 'css/img/search.png' %}">
          </div>
          <div class="col-lg-8 order-lg-1 my-auto jumbotron-text"> 
              <p class="lead">Ipsum estem berish tellun akarin balgush esun
              billish teris asterum campen mellis eberatun taram
              aspam kalemanor belin terenacum selamenIpsum estem berish tellun akarin balgush esun
              billish teris asterum campen mellis eberatun taram
              aspam kalemanor belin terenacum selamen</p>
          </div>
      </div>
      <div class="row"> <!-- Start Firts Row -->
          <div class="col-lg-4 jumbotron-img">
              <img src="{% static 'css/img/how1.png' %}">
          </div>
          <div class="col-lg-8 my-auto jumbotron-text"> 
              <p class="lead">Ipsum estem berish tellun akarin balgush esun
              billish teris asterum campen mellis eberatun taram
              aspam kalemanor belin terenacum selamenIpsum estem berish tellun akarin balgush esun
              billish teris asterum campen mellis eberatun taram
              aspam kalemanor belin terenacum selamen</p>
          </div>
      </div>
      <div class="row"> <!-- Start Firts Row -->
          <div class="col-lg-4 order-lg-2 jumbotron-img">
              <img src="{% static 'css/img/how2.png' %}">
          </div>
          <div class="col-lg-8 order-lg-1 my-auto jumbotron-text"> 
              <p class="lead">Ipsum estem berish tellun akarin balgush esun
              billish teris asterum campen mellis eberatun taram
              aspam kalemanor belin terenacum selamenIpsum estem berish tellun akarin balgush esun
              billish teris asterum campen mellis eberatun taram
              aspam kalemanor belin terenacum selamen</p>
          </div>
      </div>

  </div><!-- End Container FLuid-->
</div> <!-- End Jumbotron-->
<!-- End Section 3 Jumbotron -->

<!-- Start Call TO Action Section -->
<div class="jumbotron callto">
	<div class="col-12 narrow text-center">
		<!-- <h1>Texto Header 1</h1> -->
		<p class="lead">Learn Bootstrap by creanting with this dummy text</p>
    <a class="btn btn-secondary btn-md" href="#" target="_blank">Bootstrap Course</a>
	</div>
</div>


<!-- End Call TO Action Section -->

<!-- Star Pricing Section -->
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Pricing</h1>
  <p class="lead">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>
</div>

<div class="container">
  <div class="card-deck mb-3 text-center">

    {% for pricing in pricings %}
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">{{ pricing.name }}</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title">${{ pricing.price }} <small class="text-muted">/ mo</small></h1>
          <ul class="list-unstyled mt-3 mb-4">
            {% for feature in pricing.feature.all %}
              <li>{{ feature }}</li>
            {% endfor %}
          </ul>
          <a href="{% url 'payments:checkout' slug=pricing.slug %}"><button type="button" class="btn btn-lg btn-block btn-primary">{{ pricing.button_text }}</button></a>
        </div>
      </div>
    {% endfor %}

  </div>
</div>
<!-- End Pricing Section -->

<!--- Footer -->
<!--- Footer -->
<footer>
	<div class="container-fluid text-center">
		<div class="row text-center">
			<div class="col-md-4">
				<img src="https://getbootstrap.com/docs/4.5/assets/brand/bootstrap-solid.svg">
				<hr class="light">
				<p>555-555-5555</p>
				<p>email@email.com</p>
				<p>100 Street None</p>
				<p>City, State, 00000</p>
			</div>
			<div class="col-md-4">
				<hr class="light">
				<h5>Our hours</h5>
				<hr class="light">
				<p>Monday 9am - 5pm</p>
        <p>Saturday 10am - 4pm</p>
        <p>Monday 9am - 5pm</p>
				<p>Saturday 10am - 4pm</p>
      </div>
      <div class="col-md-4">
				<hr class="light">
				<h5>Services Area</h5>
				<hr class="light">
				<p>City, Zip Code</p>
        <p>City, Zip Code</p>
        <p>City, Zip Code</p>
				<p>City, Zip Code</p>
      </div>
      
      
    </div>
    <hr class="socket">
    &copy; Davijhon Theme.
	</div>
</footer>
<!--- Footer -->

{% endblock content %}

templates/pages/navbar.html
{% load static %}

<!-- Just an image -->
 <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="{% url 'pages:index' %}">
      <img src="{% static 'css/img/psychopedagogylogo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
    </a>


      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'pages:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pages:pricing' %}">Pricing</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pages:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pages:contact' %}">Contact</a>
          </li>
            {% if user.is_authenticated %}
              <li class="nav-dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'users:detail' request.user.username  %}">Profile</a>
                  <!-- <div class="dropdown-divider"></div> -->
                  <!-- <a class="dropdown-item" href="{# % url 'account_change_password' % #}">Change password</a> -->
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'account_logout' %}">Log Out</a>
                </div>
              </li>	          
            {% else %}
              <form class="form-inline ml-auto">
                <a href="{% url 'account_login' %}" class="btn btn-outline-secondary">Log In</a>
                <a href="{% url 'account_signup' %}" class="btn btn-primary ml-2">Sign up</a>
              </form>
            {% endif %}
      </ul>
    </div>
      
  </nav>