pages/urls.py
from django.urls import path

from .views import (
    HomeView, 
    PricingListView, 
    AboutPageView,
    ContactView,
    Suscribir
)



app_name = 'pages'
urlpatterns = [

    path('', HomeView.as_view(), name='index'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('pricing/', PricingListView.as_view(), name='pricing'),
    path('suscribirse/' ,Suscribir.as_view(), name='suscribirse'),
    
]

payment/urls.py
from django.urls import path 

from .views import (
	PaymentView, 
	CreateSubscriptionView, 
	ChangeSubscriptionView,
	RetryInvoiceView,
	webhook
)


app_name = 'payments'
urlpatterns = [

	path('plan/<slug>/', PaymentView.as_view(), name='checkout'),
	path('create-subscription/', CreateSubscriptionView.as_view(), name='create-subscription'),
	path('change-subscription/', ChangeSubscriptionView.as_view(), name='change-subscription'),
	path('retry-invoice/', RetryInvoiceView.as_view(), name='retry-invoice'),
	path('webhook/', webhook, name='webhook'),

]

users/urls.py
from django.urls import path


from .views import (
	SignupPageView,
	user_update_view,
	user_detail_view,
	user_redirect_view,
	UserSubscriptionView,
	CancelSubscriptionView,
)

app_name = 'users'
urlpatterns = [

	path("~redirect/", view=user_redirect_view, name="redirect"),
	path("~update/", view=user_update_view, name="update"),
	path("<str:username>/", view=user_detail_view, name="detail"),
	path("<str:username>/subscription/", UserSubscriptionView.as_view(), name="subscription"),
    path("<str:username>/subscription/cancel/", CancelSubscriptionView.as_view(), name="cancel-subscription"),
	path('signup/', SignupPageView.as_view(), name='signup'),

]

payment/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save, post_save
from django.contrib.auth.signals import user_logged_in
from django.utils.text import slugify
from django.shortcuts import reverse
from django.contrib.auth import get_user_model
from allauth.account.signals import email_confirmed
import stripe

stripe.api_key = settings.STRIPE_TEST_SECRET_KEY

User = get_user_model()



class Feature(models.Model):
	name = models.CharField(max_length=100)
	description = models.CharField(max_length=255)
	active = models.BooleanField(default=False)

	def __str__(self):
		return self.name


class Pricing(models.Model):
	name = models.CharField(max_length=100)  # Free / Basic / Premium
	slug = models.SlugField(unique=True)
	stripe_price_id = models.CharField(max_length=50, blank=True, null=True)
	price = models.DecimalField(decimal_places=2, max_digits=5, blank=True, null=True)
	feature = models.ManyToManyField(Feature)
	button_text = models.CharField(max_length=100)
	currency = models.CharField(max_length=50, blank=True, null=True)

	def __str__(self):
		return self.name


class Subscription(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	pricing = models.ForeignKey(Pricing, on_delete=models.CASCADE, related_name='subscriptions')
	created = models.DateTimeField(auto_now_add=True)
	stripe_subscription_id = models.CharField(max_length=50)
	status = models.CharField(max_length=100)

	def __str__(self):
		return self.user.email

	@property
	def is_active(self):
		return self.status == "active" or self.status == "trialing"


def post_email_confirmed(request, email_address, *args, **kwargs):
	user = User.objects.get(email=email_address.email)
	free_trial_pricing = Pricing.objects.get(name='Free Plan')
	subscription = Subscription.objects.create(
		user=user, 
		pricing=free_trial_pricing
	)
	stripe_customer = stripe.Customer.create(
		email=user.email
	)
	stripe_subscription = stripe.Subscription.create(
		customer=stripe_customer["id"],
		items=[{'price': 'price_1HTFm8JQrBxwDnChUzQRKkrb'}],
		trial_period_days=7
	)
	subscription.status = stripe_subscription["status"]  # trialing
	subscription.stripe_subscription_id = stripe_subscription["id"]
	subscription.save()
	user.stripe_customer_id = stripe_customer["id"]
	user.save()


def user_logged_in_receiver(sender, user, **kwargs):
    subscription = user.subscription
    sub = stripe.Subscription.retrieve(subscription.stripe_subscription_id)

    subscription.status = sub["status"]
    subscription.save()

user_logged_in.connect(user_logged_in_receiver)
email_confirmed.connect(post_email_confirmed)

payment/views.py
import json
from django.conf import settings
from django.views.generic import TemplateView, View
from django.http import JsonResponse, HttpResponse
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404, redirect, render
from rest_framework.views import APIView
from rest_framework.response import Response
import stripe

from .models import Pricing
from .utils import sending_info_plan

User = get_user_model()
stripe.api_key = settings.STRIPE_TEST_SECRET_KEY



@csrf_exempt
def webhook(request):
	# You can use webhooks to receive information about asynchronous payment events.
	# For more about our webhook events check out https://stripe.com/docs/webhooks.
	webhook_secret = settings.STRIPE_WEBHOOK_SECRET
	payload = request.body

	# Retrieve the event by verifying the signature using the raw body and secret if webhook signing is configured.
	signature = request.META['HTTP_STRIPE_SIGNATURE']

	try:
		event = stripe.Webhook.construct_event(
			payload=payload, sig_header=signature, secret=webhook_secret
		)
		data = event['data']
	except stripe.error.SignatureVerificationError as e:
		return e
	except Exception as e:
		return e
		
	# Get the type of webhook event sent - used to check the status of PaymentIntents.
	event_type = event['type']
	data_object = data['object']

	if event_type == 'invoice.paid':
		# Used to provision services after the trial has ended.
		# The status of the invoice will show up as paid. Store the status in your
		# database to reference when a user accesses your service to avoid hitting rate
		# limits.
		# TODO: change the users subscription and pricing

		webhook_object = data["object"]
		stripe_customer_id = webhook_object["customer"]

		stripe_sub = stripe.Subscription.retrieve(webhook_object["subscription"])
		stripe_price_id = stripe_sub["plan"]["id"]

		pricing = Pricing.objects.get(stripe_price_id=stripe_price_id)

		
		user = User.objects.get(stripe_customer_id=stripe_customer_id)
		user.subscription.status = stripe_sub["status"]
		user.subscription.stripe_subscription_id = webhook_object["subscription"]
		user.subscription.pricing = pricing
		user.subscription.save()
		
		sending_info_plan(user, stripe_sub, event_type, pricing)

	if event_type == 'invoice.finalized':
		# If you want to manually send out invoices to your customers
		# or store them locally to reference to avoid hitting Stripe rate limits.
		print(data)

	if event_type == 'customer.subscription.deleted':
		# handle subscription cancelled automatically based
		# upon your subscription settings. Or if the user cancels it.
		webhook_object = data["object"]
		stripe_customer_id = webhook_object["customer"]
		stripe_sub = stripe.Subscription.retrieve(webhook_object["id"])
		user = User.objects.get(stripe_customer_id=stripe_customer_id)
		user.subscription.status = stripe_sub["status"]
		user.subscription.save()

	if event_type == 'customer.subscription.trial_will_end':
		# Send notification to your user that the trial will end
		print(data)

	if event_type == 'customer.subscription.updated':
		# if customer chance his plan, update the DB.		
		webhook_object = data["object"]
		print(webhook_object)
		stripe_customer_id = webhook_object["customer"]

		stripe_sub = stripe.Subscription.retrieve(webhook_object["id"])
		stripe_price_id = stripe_sub["plan"]["id"]

		pricing = Pricing.objects.get(stripe_price_id=stripe_price_id)

		user = User.objects.get(stripe_customer_id=stripe_customer_id)

		current_plan = user.subscription.pricing.name

		user.subscription.status = stripe_sub["status"]
		user.subscription.stripe_subscription_id = webhook_object["id"]
		user.subscription.pricing = pricing
		user.subscription.save()

		sending_info_plan(user, stripe_sub, event_type, pricing, current_plan=current_plan)

	return HttpResponse()


class PaymentView(LoginRequiredMixin, View):

	def get(self, request, slug, *args, **kwargs):
		subscription = self.request.user.subscription
		pricing = get_object_or_404(Pricing, slug=slug)

		if subscription.pricing == pricing and subscription.is_active:
			messages.info(self.request, "You are already enrolled for this package")
			return redirect("pages:pricing")

		context = {
			"pricing_tier": pricing,
			"STRIPE_PUBLIC_KEY": settings.STRIPE_TEST_PUBLIC_KEY
		}

		if subscription.is_active and subscription.pricing.stripe_price_id != "django-free-trial":
			return render(self.request, "payments/change.html", context)
	
		return render(self.request, "payments/checkout.html", context)


class CreateSubscriptionView(APIView):
	def post(self, request, *args, **kwargs):
		data = request.data
		customer_id = request.user.stripe_customer_id
		try:
			# Attach the payment method to the customer
			stripe.PaymentMethod.attach(
				data['paymentMethodId'],
				customer=customer_id,
			)
			# Set the default payment method on the customer
			stripe.Customer.modify(
				customer_id,
				invoice_settings={
					'default_payment_method': data['paymentMethodId'],
				},
			)

			# Create the subscription
			subscription = stripe.Subscription.create(
				customer=customer_id,
				items=[{'price': data["priceId"]}],
				expand=['latest_invoice.payment_intent'],
			)

			data = {}
			print('I am here')
			data.update(subscription)
			return Response(data)
		except Exception as e:
			return Response({
				"error": {'message': str(e)}
			})


class ChangeSubscriptionView(APIView):
	def post(self, request, *args, **kwargs):
		print(request.data)
		subscription_id = request.user.subscription.stripe_subscription_id
		subscription = stripe.Subscription.retrieve(subscription_id)
		try:
			updatedSubscription = stripe.Subscription.modify(
				subscription_id,
				cancel_at_period_end=False,
				items=[{
					'id': subscription['items']['data'][0].id,
					'price': request.data["priceId"],
				}],
				proration_behavior="always_invoice"
			)

			data = {}

			data.update(updatedSubscription)

			return Response(data)
		except Exception as e:
			return Response({
				"error": {'message': str(e)}
			})


class RetryInvoiceView(APIView):
	def post(self, request, *args, **kwargs):
		data = request.data
		customer_id = request.user.stripe_customer_id
		try:

			stripe.PaymentMethod.attach(
				data['paymentMethodId'],
				customer=customer_id,
			)
			# Set the default payment method on the customer
			stripe.Customer.modify(
				customer_id,
				invoice_settings={
					'default_payment_method': data['paymentMethodId'],
				},
			)

			invoice = stripe.Invoice.retrieve(
				data['invoiceId'],
				expand=['payment_intent'],
			)
			data = {}
			data.update(invoice)

			return Response(data)
		except Exception as e:

			return Response({
				"error": {'message': str(e)}
			})

templates/payments/checkout.html
{% extends "base.html" %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/stripe.css' %}" />
<script src="https://js.stripe.com/v3/"></script>
{% endblock extra_head %}

{% block content %}
  <div class="flex justify-center mx-auto">
    <div class="py-3">
      <div class="border border-gray-200 rounded shadow-md px-3 py-3">
        <h2 class="text-xl text-center text-gray-500">
          Enroll for the {{ pricing_tier.name }} membership
        </h2>
        <p class="text-3xl text-center text-gray-800">
          {% if pricing_tier.currency == "usd" %}
          ${{ pricing_tier.price }}/mo
          {% else %}
          €{{ pricing_tier.price }}/mo
          {% endif %}
        </p>
      </div>
      <div class="mt-3">
        <form id="subscription-form">
          {% csrf_token %}
          <div id="card-element"><!--Stripe.js injects the Card Element--></div>
          <button id="submit" type="submit">
              <div class="spinner hidden" id="spinner"></div>
              <span id="button-text">Pay</span>
          </button>
          <p id="card-errors" role="alert"></p>
        </form>
      </div>
    </div>
  </div>
  {% include 'pages/footer.html' %}
{% endblock content %}

{% block javascript %}
<script>

const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

var stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
var elements = stripe.elements();

// Set up Stripe.js and Elements to use in checkout form
var style = {
  base: {
    color: "#32325d",
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: "antialiased",
    fontSize: "16px",
    "::placeholder": {
      color: "#aab7c4"
    }
  },
  invalid: {
    color: "#fa755a",
    iconColor: "#fa755a"
  }
};

var priceId = "{{ pricing_tier.stripe_price_id }}"

var card = elements.create("card", { style: style });
card.mount("#card-element");

card.on('change', showCardError);

function showCardError(event) {
  let displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
}

var form = document.getElementById('subscription-form');

form.addEventListener('submit', function (ev) {
  ev.preventDefault();
  changeLoadingState(true);

  // If a previous payment was attempted, get the latest invoice
  const latestInvoicePaymentIntentStatus = localStorage.getItem(
    'latestInvoicePaymentIntentStatus'
  );

  if (latestInvoicePaymentIntentStatus === 'requires_payment_method') {
    const invoiceId = localStorage.getItem('latestInvoiceId');
    const isPaymentRetry = true;
    // create new payment method & retry payment on invoice with new payment method
    createPaymentMethod({
      card,
      isPaymentRetry,
      invoiceId,
    });
  } else {
    // create new payment method & create subscription
    createPaymentMethod({ card });
  }
});

function createPaymentMethod({ card, isPaymentRetry, invoiceId }) {
  // Set up payment method for recurring usage

  stripe
    .createPaymentMethod({
      type: 'card',
      card: card,
    })
    .then((result) => {
      if (result.error) {
        changeLoadingState(false);
        displayError(result);
      } else {
        if (isPaymentRetry) {
          // Update the payment method and retry invoice payment
          retryInvoiceWithNewPaymentMethod({
            paymentMethodId: result.paymentMethod.id,
            invoiceId: invoiceId,
            priceId: priceId,
          });
        } else {
          // Create the subscription
          createSubscription({
            paymentMethodId: result.paymentMethod.id,
            priceId: priceId,
          });
        }
      }
    });
}

function createSubscription({ paymentMethodId, priceId }) {
  return (
    fetch("{% url 'payment:create-subscription' %}", {
      method: 'post',
      headers: {
        'Content-Type': "application/json",
        'X-CSRFToken': csrftoken
      },
      body: JSON.stringify({
        paymentMethodId: paymentMethodId,
        priceId: priceId,
      }),
    })
      .then((response) => {
        return response.json();
      })
      // If the card is declined, display an error to the user.
      .then((result) => {
        if (result.error) {
          // The card had an error when trying to attach it to a customer.
          throw result;
        }
        return result;
      })
      // Normalize the result to contain the object returned by Stripe.
      // Add the additional details we need.
      .then((result) => {
        return {
          paymentMethodId: paymentMethodId,
          priceId: priceId,
          subscription: result,
        };
      })
      // Some payment methods require a customer to be on session
      // to complete the payment process. Check the status of the
      // payment intent to handle these actions.
      .then(handlePaymentThatRequiresCustomerAction)
      // If attaching this card to a Customer object succeeds,
      // but attempts to charge the customer fail, you
      // get a requires_payment_method error.
      .then(handleRequiresPaymentMethod)
      // No more actions required. Provision your service for the user.
      .then(onSubscriptionComplete)
      .catch((error) => {
        changeLoadingState(false);
        // An error has happened. Display the failure to the user here.
        // We utilize the HTML element we created.
        showCardError(error);
      })
  );
}

function handlePaymentThatRequiresCustomerAction({
  subscription,
  invoice,
  priceId,
  paymentMethodId,
  isRetry,
}) {
  if (subscription && subscription.status === 'active') {
    // Subscription is active, no customer actions required.
    return { subscription, priceId, paymentMethodId };
  }

  // If it's a first payment attempt, the payment intent is on the subscription latest invoice.
  // If it's a retry, the payment intent will be on the invoice itself.
  let paymentIntent = invoice ? invoice.payment_intent : subscription.latest_invoice.payment_intent;

  if (
    paymentIntent.status === 'requires_action' ||
    (isRetry === true && paymentIntent.status === 'requires_payment_method')
  ) {
    return stripe
      .confirmCardPayment(paymentIntent.client_secret, {
        payment_method: paymentMethodId,
      })
      .then((result) => {
        if (result.error) {
          // Start code flow to handle updating the payment details.
          // Display error message in your UI.
          // The card was declined (i.e. insufficient funds, card has expired, etc).
          throw result;
        } else {
          if (result.paymentIntent.status === 'succeeded') {
            // Show a success message to your customer.
            // There's a risk of the customer closing the window before the callback.
            // We recommend setting up webhook endpoints later in this guide.
            return {
              priceId: priceId,
              subscription: subscription,
              invoice: invoice,
              paymentMethodId: paymentMethodId,
            };
          }
        }
      })
      .catch((error) => {
        changeLoadingState(false);
        displayError(error);
      });
  } else {
    // No customer action needed.
    return { subscription, priceId, paymentMethodId };
  }
}

function handleRequiresPaymentMethod({
  subscription,
  paymentMethodId,
  priceId,
}) {
  if (subscription.status === 'active') {
    // subscription is active, no customer actions required.
    return { subscription, priceId, paymentMethodId };
  } else if (
    subscription.latest_invoice.payment_intent.status ===
    'requires_payment_method'
  ) {
    // Using localStorage to manage the state of the retry here,
    // feel free to replace with what you prefer.
    // Store the latest invoice ID and status.
    localStorage.setItem('latestInvoiceId', subscription.latest_invoice.id);
    localStorage.setItem(
      'latestInvoicePaymentIntentStatus',
      subscription.latest_invoice.payment_intent.status
    );
    throw { error: { message: 'Your card was declined.' } };
  } else {
    return { subscription, priceId, paymentMethodId };
  }
}

function onSubscriptionComplete(result) {
  // Payment was successful.
  if (result.subscription.status === 'active') {
      console.log("Complete")
      window.location.href = "{% url 'users:detail' request.user.username %}"
    // Change your UI to show a success message to your customer.
    // Call your backend to grant access to your service based on
    // `result.subscription.items.data[0].price.product` the customer subscribed to.
  }
}

function retryInvoiceWithNewPaymentMethod({
  paymentMethodId,
  invoiceId,
  priceId
}) {
  return (
    fetch("{% url 'payment:retry-invoice' %}", {
      method: 'post',
      headers: {
        'Content-Type': "application/json",
        'X-CSRFToken': csrftoken
      },
      body: JSON.stringify({
        paymentMethodId: paymentMethodId,
        invoiceId: invoiceId,
      }),
    })
      .then((response) => {
        return response.json();
      })
      // If the card is declined, display an error to the user.
      .then((result) => {
        if (result.error) {
          // The card had an error when trying to attach it to a customer.
          throw result;
        }
        return result;
      })
      // Normalize the result to contain the object returned by Stripe.
      // Add the additional details we need.
      .then((result) => {
        return {
          // Use the Stripe 'object' property on the
          // returned result to understand what object is returned.
          invoice: result,
          paymentMethodId: paymentMethodId,
          priceId: priceId,
          isRetry: true,
        };
      })
      // Some payment methods require a customer to be on session
      // to complete the payment process. Check the status of the
      // payment intent to handle these actions.
      .then(handlePaymentThatRequiresCustomerAction)
      // No more actions required. Provision your service for the user.
      .then(onSubscriptionComplete)
      .catch((error) => {
        changeLoadingState(false);
        // An error has happened. Display the failure to the user here.
        // We utilize the HTML element we created.
        displayError(error);
      })
  );
}

function changeLoadingState(isLoading) {
  if (isLoading) {
    document.querySelector('#button-text').classList.add('hidden');
    document.querySelector('#spinner').classList.remove('hidden');
    document.querySelector('#subscription-form button').disabled = true;
  } else {
    document.querySelector('#button-text').classList.remove('hidden');
    document.querySelector('#spinner').classList.add('hidden');
    document.querySelector('#subscription-form button').disabled = false;
  }
}

</script>

{% endblock javascript %}