pages/urls.py
from django.urls import path

from .views import (
    HomeView, 
    PricingListView, 
    AboutPageView,
    ContactView,
    Suscribir
)



app_name = 'pages'
urlpatterns = [

    path('', HomeView.as_view(), name='index'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('pricing/', PricingListView.as_view(), name='pricing'),
    path('suscribirse/' ,Suscribir.as_view(), name='suscribirse'),
    
]

users/urls.py
from django.urls import path


from .views import (
	SignupPageView,
	user_update_view,
	user_detail_view,
	user_redirect_view,
	UserSubscriptionView,
	CancelSubscriptionView,
)

app_name = 'users'
urlpatterns = [

	path("~redirect/", view=user_redirect_view, name="redirect"),
	path("~update/", view=user_update_view, name="update"),
	path("<str:username>/", view=user_detail_view, name="detail"),
	path("<str:username>/subscription/", UserSubscriptionView.as_view(), name="subscription"),
    path("<str:username>/subscription/cancel/", CancelSubscriptionView.as_view(), name="cancel-subscription"),
	path('signup/', SignupPageView.as_view(), name='signup'),

]

users/models.py
from django.db import models
from django.urls import reverse
from django.db.models import CharField
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
	#: First and last name do not cover name patterns around the globe
	name = CharField(max_length=255, blank=True)
	stripe_customer_id = CharField(max_length=50)

	def get_absolute_url(self):
		"""Get url for user's detail view.
		Returns:
			str: URL for user detail.
		"""
		return reverse("users:detail", kwargs={"username": self.username})

users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError 
from django import forms as normal_forms



User = get_user_model()



class CancelSubscriptionForm(normal_forms.Form):
	hidden = normal_forms.HiddenInput()


class CustomUserCreationForm(forms.UserCreationForm):

	error_message = forms.UserCreationForm.error_messages.update(
		{"duplicate_username": ("This username has already been taken.")}
	)

	class Meta(forms.UserCreationForm.Meta):
		model = User

	def clean_username(self):
		username = self.cleaned_data["username"]

		try:
			User.objects.get(username=username)
		except User.DoesNotExist:
			return username

		raise ValidationError(self.error_messages["duplicate_username"])


class CustomUserChangeForm(forms.UserChangeForm):

	class Meta(forms.UserChangeForm.Meta):
		model = User

users/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, RedirectView, UpdateView, CreateView, FormView
#from django.views.generic import FormView

from .forms import CustomUserCreationForm, CancelSubscriptionForm

import stripe

User = get_user_model()
stripe.api_key = settings.STRIPE_TEST_SECRET_KEY


class CancelSubscriptionView(LoginRequiredMixin, FormView):
    form_class = CancelSubscriptionForm

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def form_valid(self, form):
        stripe.Subscription.delete(self.request.user.subscription.stripe_subscription_id)
        messages.success(self.request, "You have successfully cancelled your subscription")
        return super().form_valid(form)


class UserSubscriptionView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = "users/user_subscription.html"


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, ("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class SignupPageView(CreateView):
	form_class = CustomUserCreationForm
	success_url = reverse_lazy('pages:index')
	template_name = 'account/signup.html'

templates/users/customuser_detail.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div id="wrapper">

  <!-- Sidebar -->
  <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
          <li class="sidebar-brand">
              <a href="#">
                  Start Bootstrap
              </a>
          </li>
          <li>
              <a href="#">Dashboard</a>
          </li>
          <li>
              <a href="{% url 'users:update' %}">My info</a>
          </li>
          <li>
              <a href="{% url 'account_email' %}">E-Mail</a>
          </li>
          <li>
              <a href="{% url 'users:subscription' request.user.username %}">My subscription</a>
          </li>
      </ul>
  </div>
  <!-- /#sidebar-wrapper -->

  <!-- Page Content -->
  <div id="page-content-wrapper">
      <div class="container-fluid">
          <div class="row">
              <div class="col-lg-12">
                  <h1>{{ object.username }}</h1>
                  <p>This template has a responsive menu toggling system. The menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will appear/disappear. On small screens, the page content will be pushed off canvas.</p>
                  <p>Make sure to keep all page content within the <code>#page-content-wrapper</code>.</p>
                  <a href="#menu-toggle" class="btn btn-primary" id="menu-toggle">My Profile</a>
              </div>
          </div>
      </div>
  </div>
  <!-- /#page-content-wrapper -->

</div>




</div>
{% endblock content %}

{% block extra_javascript %}
<script>
  $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
  });
  </script>
{% endblock extra_javascript %}

templates/users/customuser_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}{{ user.username }}{% endblock %}


{% block content %}
	<h1>{{ user.username }}</h1>
	<form class="form-horizontal" method="post" action="{% url 'users:update' %}">
		{% csrf_token %}
		{{ form|crispy }}
		<div class="control-group">
			<div class="controls">
				<button type="submmit" class="btn btn-primary">
					Update
				</button>
			</div>
		</div>
	</form>
{% endblock content %}

templates/users/user_subscription.html
{% extends 'base.html' %}
{% load static %}


{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">
    <div>
        {% if object == request.user %}

            <div class="row">
                <div class="col-sm-12">
                    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
                    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-mail</a>
                    <a class="btn btn-primary" href="{% url 'users:subscription' request.user.username %}" role="button">My subscription</a>
                </div>
            </div>

        {% endif %}	

        <h2>Package: {{ user.subscription.pricing.name }}</h2>

        <h3>Status: {{ user.subscription.status }}</h3>
        {% if user.subscription.status != 'canceled' %}
            <form method="post" class="py-3 mt-3" action="{% url 'users:cancel-subscription' request.user.username %}">
                {% csrf_token %}
                {{ form }}
                <button  class="btn btn-primary"  type="submit">
                    Cancel Subscription
                </button>
            </form>
        {% endif %}

    </div>
</div>
{% endblock content %}